name: Generate ISO
description: Creates an ISO for installing an OSTree container

inputs:
  ARCH:
    description: Architecture for image to build
    required: true
    default: x86_64
  IMAGE_NAME:
    description: Name of the source container image
    required: true
    default: base-main
  IMAGE_REPO:
    description: Repository containing the source container image
    required: true
    default: ghcr.io/ublue-os
  VARIANT:
    description: "Source container variant. Available options can be found by running `dnf provides system-release`. Variant will be the third item in the package name. Example: `fedora-release-kinoite-39-34.noarch` will be kinonite"
    required: true
    default: Kinoite
  VERSION:
    description: Fedora version of installer to build
    required: true
    default: "39"
  IMAGE_TAG:
    description: Tag of the source container image
    required: false
  EXTRA_BOOT_PARAMS:
    description: Extra params used by grub to boot the anaconda installer
    required: false
  WEB_UI:
    description: Enable Anaconda WebUI
    required: true
    default: "false"
  ENROLLMENT_PASSWORD:
    description: Used for supporting secure boot (requires SECURE_BOOT_KEY_URL to be defined)
    required: false
    default: "ublue-os"
  SECURE_BOOT_KEY_URL:
    description: Secure boot key that is installed from URL location
    required: false
  ACTION_REPO:
    deprecationMessage: This variable is no longer used and will be removed in a future version
    required: false
  ACTION_REF:
    deprecationMessage: This variable is no longer used and will be removed in a future version
    required: false
  FLATPAK_REMOTE_NAME:
    description: Name of the Flatpak remote repo
    required: false
    default: "flathub"
  FLATPAK_REMOTE_URL:
    description: The URL of the Flatpak remote flatpakrepo file
    required: false
    default: https://flathub.org/repo/flathub.flatpakrepo
  FLATPAK_REMOTE_REFS:
    description: Space delimited list of refs to the flatpak packages to install
    required: false
    default: ""

outputs:
  output-directory:
    value: ${{ steps.final.outputs.OUTPUT_DIR }}
  iso-path: 
    value: ${{ steps.final.outputs.ISO_PATH }}
  checksum-path: 
    value: ${{ steps.final.outputs.CHECKSUM_PATH }} 

runs:
  using: composite
  steps:
    - name: Run docker image and generate sha256 checksum
      shell: bash
      id: final
      working-directory: ${{ github.action_path }}
      run: |
        # Check if running inside of the action repo
        if [[ -z "${{ github.action_ref }}" ]]; then if [[ "${{ github.ref_name }}" =~ (.*)/merge ]]; then tag=pr-${BASH_REMATCH[1]}; else tag=${{ github.ref_name }}; fi; fi
        if [[ -z "${tag}" ]]; then tag=${{ github.action_ref }}; fi
        docker run --privileged --volume .:/isogenerator/output \
          -e ARCH=${{ inputs.arch }} \
          -e IMAGE_NAME=${{ inputs.image_name }} \
          -e IMAGE_REPO=${{ inputs.image_repo }} \
          -e VARIANT=${{ inputs.variant }} \
          -e VERSION=${{ inputs.version }} \
          -e IMAGE_TAG=${{ inputs.image_tag || inputs.version }} \
          -e WEB_UI=${{ inputs.web_ui }} \
          -e FLATPAK_REMOTE_NAME=${{ inputs.flatpak_remote_name }} \
          -e FLATPAK_REMOTE_URL=${{ inputs.flatpak_remote_url }} \
          -e FLATPAK_REMOTE_REFS="${{ inputs.flatpak_remote_refs }}" \
          ghcr.io/jasonn3/build-container-installer:${tag}
        mkdir end_iso
        sha256sum ${{ inputs.IMAGE_NAME }}-${{ inputs.IMAGE_TAG || inputs.VERSION }}.iso > ./end_iso/${{ inputs.IMAGE_NAME }}-${{ inputs.IMAGE_TAG || inputs.VERSION }}-CHECKSUM
        mv ${{ inputs.IMAGE_NAME }}-${{ inputs.IMAGE_TAG || inputs.VERSION }}.iso end_iso/
        
        echo "OUTPUT_DIR=$(realpath ./end_iso)" >> $GITHUB_OUTPUT
        echo "ISO_PATH=$(realpath ./end_iso/${{ inputs.IMAGE_NAME }}-${{ inputs.IMAGE_TAG || inputs.VERSION }}.iso)" >> $GITHUB_OUTPUT
        echo "CHECKSUM_PATH=$(realpath ./end_iso/${{ inputs.IMAGE_NAME }}-${{ inputs.IMAGE_TAG || inputs.VERSION }}-CHECKSUM)" >> $GITHUB_OUTPUT
