name: Generate Bazzite ISO
on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Free Disk Space (Bash script)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/swift
          sudo rm -rf /root/.dotnet
          sudo rm -rf /opt/pipx
          sudo rm -rf /usr/local/share/vcpkg
          docker image prune --all --force

      - name: Checkout Isogenerator Source Code
        uses: actions/checkout@v4

      - name: Build ISO Image
        run: |
          mkdir -p ${{ github.workspace }}/output
          
          # Запускаем модифицированную команду. 
          # Мы добавили bash-команду внутрь контейнера, которая удаляет проблемный пакет из списка до запуска Lorax
          docker run --rm --privileged \
            -v "${{ github.workspace }}/output:/isogenerator/output" \
            -e OCI_REPO="ghcr.io/ublue-os/bazzite-deck" \
            -e VERSION="43" \
            -e IMAGE_TAG="43.20260420" \
            -e VARIANT="bazzite-deck" \
            --entrypoint /bin/bash \
            ghcr.io/ublue-os/isogenerator:latest \
            -c "sed -i '/polkit-gnome/d' /usr/share/lorax/templates.d/99-generic/runtime-install.tmpl && /isogenerator/build.sh"

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bazzite-iso-43.20260420
          path: ${{ github.workspace }}/output/*.iso
          retention-days: 2
