name: Generate Bazzite 43 ISO
on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Free Disk Space (Bash script)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/swift
          sudo rm -rf /root/.dotnet
          sudo rm -rf /opt/pipx
          sudo rm -rf /usr/local/share/vcpkg
          docker image prune --all --force

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build ISO via Native BlueBuild Action
        uses: blue-build/github-action@v1.2.0
        with:
          # Указываем только имя, экшен сам будет искать в ./config/recipes/bazzite.yml
          recipe: 'bazzite.yml'
          cli_version: 'v0.9.5'
          compile: false
          is_iso: true
          iso_image_tag: '43.20260420'
          iso_fedora_version: '43'

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bazzite-deck-43.20260420-ISO
          path: |
            *.iso
            **/*.iso
          retention-days: 2
